#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
export DJANGO_SUPERUSER_EMAIL=admin@example.com
export DJANGO_SUPERUSER_USERNAME=admin
export DJANGO_SUPERUSER_PASSWORD=admin
python manage.py createsuperuser --noinput || true
python manage.py runserver 0.0.0.0:8000