# Generated by Django 5.0 on 2023-12-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0004_apisettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiSettings',
            new_name='TodoApiSettings',
        ),
    ]
