# Generated by Django 5.0 on 2023-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0006_rename_todoapisettings_todoapisetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
