# Generated by Django 5.0 on 2023-12-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_apisettings_todoapisettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoApiSettings',
            new_name='TodoApiSetting',
        ),
    ]
